language: php

php:
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
    - php: 7

before_script:
  - wget http://peridot-php.github.io/downloads/peridot.phar

install:
  - composer install --prefer-source

script:
  - php peridot.phar specs/
